# Generated by Django 4.1.3 on 2022-12-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_alter_post_conteudo_alter_post_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculadoraForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=30)),
                ('anos', models.CharField(max_length=3)),
                ('altura', models.CharField(max_length=3)),
                ('peso', models.CharField(max_length=3)),
                ('pescoco', models.CharField(max_length=3)),
                ('cintura', models.CharField(max_length=3)),
                ('quadril', models.CharField(max_length=3)),
                ('objetivo', models.CharField(choices=[('Manter peso', 'Manter peso'), ('Perder peso (leve)', 'Perder peso (leve)'), ('Perde peso', 'Perde peso'), ('Ganhar peso (leve)', 'Ganhar peso (leve)'), ('Ganhar peso', 'Ganhar peso')], max_length=30)),
                ('atividade', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Levemente ativo', 'Levemente ativo'), ('Moderadamente', 'Moderadamente'), ('Muito ativo', 'Muito ativo'), ('Extremanente', 'Extremanente')], max_length=30)),
            ],
        ),
    ]
