# Generated by Django 4.1.3 on 2022-12-14 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit', '0004_perfil_delete_calculadoraforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
