# Generated by Django 4.1.3 on 2022-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_alter_perfil_altura_alter_perfil_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='atividade_fisica',
            field=models.CharField(choices=[('sedentario', 'sedentario'), ('levemente ativo', 'levemente ativo'), ('moderadamente', 'moderadamente'), ('muito ativo', 'muito ativo'), ('extremamente', 'extremamente')], default='Feminino', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
