# Generated by Django 4.1.3 on 2022-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_perfil_atividade_fisica_perfil_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
